name: Build and Release Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Zipar a extensão
        run: |
          cd extension
          zip -r ../PromoPulse-Extension-${{ github.ref_name }}.zip ./*

      - name: Criar Release no GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: PromoPulse-Extension-${{ github.ref_name }}.zip
          generate_release_notes: true